# Generated by Django 3.0.4 on 2020-03-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsai', '0002_auto_20200325_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exID', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('primary', models.CharField(max_length=64)),
                ('secondary', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=32)),
                ('amount_required', models.IntegerField()),
                ('business_type', models.CharField(choices=[('', 'Choose...'), ('FT', 'Food Truck'), ('CON', 'Construction'), ('OTH', 'Other')], max_length=3)),
                ('years_in_business', models.IntegerField()),
                ('other', models.CharField(max_length=64)),
                ('agree', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('value', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsai.Exercise')),
            ],
        ),
    ]
