# Generated by Django 2.2.12 on 2020-04-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsai', '0003_exercise_loan_logentry_routineexercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='FirstName',
            new_name='First',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='LastName',
            new_name='Last',
        ),
    ]
